// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddAccountFromURI(arg1) {
  return window['go']['main']['App']['AddAccountFromURI'](arg1);
}

export function ClearClipboard() {
  return window['go']['main']['App']['ClearClipboard']();
}

export function CopyCode(arg1) {
  return window['go']['main']['App']['CopyCode'](arg1);
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetCodes() {
  return window['go']['main']['App']['GetCodes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetLaunchScreenshotProtection(arg1) {
  return window['go']['main']['App']['SetLaunchScreenshotProtection'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}
